server {
    listen 80;

    server_name localhost;

    location /product/ {
        proxy_pass http://product-service:8000/;
    }

    location /user/ {
        proxy_pass http://user-service:8000/;
    }

    location /order/ {
        proxy_pass http://order-service:8000/;
    }
    # Serve static files directly
    location /static/ {
        alias /app/static/;
    }
}