events {}

http {
    upstream frontend {
        server frontend:3000;
    }

    upstream user_service {
        server users:8000;
    }

    upstream product_service {
        server products:8000;
    }

    upstream order_service {
        server orders:8000;
    }

    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://client-service;
        }

        # Microservices routing
        location /api/users/ {
            proxy_pass http://users_service;
        }

        location /api/products/ {
            proxy_pass http://products_service;
        }

        location /api/orders/ {
            proxy_pass http://orders_service;
        }
    }
}